services:

  nginx-react:
    container_name: nginx-react
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
